# Generated by Django 5.1.6 on 2025-03-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_questao', models.IntegerField(unique=True)),
                ('classificacao', models.CharField(max_length=20)),
            ],
        ),
    ]
