# Generated by Django 5.1.6 on 2025-04-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='ano',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classificacao',
            name='disciplina',
            field=models.CharField(default='Desconhecido', max_length=50),
        ),
    ]
