# Generated by Django 5.1.6 on 2025-04-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_classificacao_ano_classificacao_disciplina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classificacao',
            old_name='disciplina',
            new_name='area_conhecimento',
        ),
    ]
