# Generated by Django 5.1.6 on 2025-04-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_rename_disciplina_classificacao_area_conhecimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacao',
            name='ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classificacao',
            name='area_conhecimento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classificacao',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classificacao',
            name='numero_questao',
            field=models.IntegerField(),
        ),
    ]
