# Generated by Django 5.1.6 on 2025-05-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0004_alter_classificacao_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='classificacao',
            constraint=models.UniqueConstraint(fields=('numero_questao', 'ano', 'area_conhecimento'), name='unique_classificacao'),
        ),
    ]
